"""phase3_ai_schema

Revision ID: 654c737578d9
Revises: 0088fbc1c310
Create Date: 2026-10-05 22:48:16.149150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654c737578d9'
down_revision: Union[str, Sequence[str], None] = '0088fbc1c310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_type'), 'notifications', ['recipient_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('ai_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('base_schedule_version_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='aiproposalstatusenum'), nullable=False),
    sa.Column('proposal_json', sa.JSON(), nullable=False),
    sa.Column('validation_result_json', sa.JSON(), nullable=False),
    sa.Column('observability_json', sa.JSON(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_proposals_base_schedule_version_id'), 'ai_proposals', ['base_schedule_version_id'], unique=False)
    op.create_index(op.f('ix_ai_proposals_status'), 'ai_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_proposals_status'), table_name='ai_proposals')
    op.drop_index(op.f('ix_ai_proposals_base_schedule_version_id'), table_name='ai_proposals')
    op.drop_table('ai_proposals')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
